static_host_map:
  '192.168.100.1': ['198.51.100.1:4242']

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - '192.168.100.1'

listen:
  host: 0.0.0.0
  port: 4243

firewall:
  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any

pki:
  ca: /ca.crt
  cert: /host1.crt
  key: /host1.key

tun:
  disabled: true